module.exports = {
    rules: {
        'array-bracket-spacing': ['error', 'never'],
        'block-spacing': ['error', 'always'],
        'brace-style': ['error', '1tbs', { 'allowSingleLine': true }],
        'camelcase': ['error', {'properties': 'always'}],
        'comma-spacing': ['error', { 'before': false, 'after': true }],
        'comma-style': ['error', 'last'],
        'computed-property-spacing': ['error', 'never'],
        'consistent-this': ['error', 'self'],
        'eol-last': ['error'],
        'func-names': ['off'],
        'func-style': ['error', 'declaration', { 'allowArrowFunctions': true }],
        'id-blacklist': ['off'],
        'id-length': ['off'],
        'id-match': ['off'],
        'indent': ['error', 4],
        'jsx-quotes': ['off'],
        'key-spacing': ['error', { 'beforeColon': false, 'afterColon': true }],
        'keyword-spacing': ['error', { 'before': true, 'after': true }],
        'linebreak-style': ['error', 'unix'],
        'lines-around-comment': ['off'],
        'max-depth': ['warn', { 'max': 10 }],
        'max-len': ['error', 79],
        'max-nested-callbacks': ['warn', { 'max': 5 }],
        'max-params': ['off'],
        'max-statements': ['off'],
        'max-statements-per-line': ['warn', { 'max': 2 }],
        'new-cap': ['off'],
        'new-parens': ['error'],
        'newline-after-var': ['off'],
        'newline-before-return': ['off'],
        'newline-per-chained-call': ['off'],
        'no-array-constructor': ['warn'],
        'no-bitwise': ['warn', { 'allow': ['~', '>>', '<<', '^'] }],
        'no-continue': ['off'],
        'no-inline-comments': ['warn'],
        'no-lonely-if': ['off'],
        'no-mixed-spaces-and-tabs': ['error'],
        'no-multiple-empty-lines': ['warn', { 'max': 3 }],
        'no-negated-condition': ['error'],
        'no-nested-ternary': ['warn'],
        'no-new-object': ['warn'],
        'no-plusplus': ['error', { 'allowForLoopAfterthoughts': true }],
        'no-restricted-syntax': ['off'],
        'no-spaced-func': ['error'],
        'no-ternary': ['off'],
        'no-trailing-spaces': ['error'],
        'no-underscore-dangle': ['off'],
        'no-unneeded-ternary': ['warn'],
        'no-whitespace-before-property': ['error'],
        'object-curly-spacing': ['error', 'always'],
        'one-var': ['error', 'never'],
        'one-var-declaration-per-line': ['error', 'always'],
        'operator-assignment': ['warn', 'always'],
        'operator-linebreak': ['error', 'before'],
        'padded-blocks': ['off'],
        'quote-props': ['error', 'as-needed'],
        'quotes': ['error', 'single', { 'allowTemplateLiterals': true }],
        'require-jsdoc': ['off'],
        'semi': ['error', 'always'],
        'semi-spacing': ['error', { 'before': false, 'after': true }],
        'sort-imports': ['off'],
        'soft-vars': ['off'],
        'space-before-blocks': ['error', 'always'],
        'space-before-function-paren': ['error', 'never'],
        'space-in-parens': ['error', 'never'],
        'space-infix-ops': ['error'],
        'space-unary-ops': ['error', { 'words': true }],
        'spaced-comment': ['error', 'always'],
        'wrap-regex': ['off']
    }
};
